# Generated by Django 6.0.4 on 2026-05-12 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название локации')),
                ('lat', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Долгота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Локация пользователя',
                'verbose_name_plural': 'Локации пользователей',
                'ordering': ['-id'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
