# Generated by Django 6.0.4 on 2026-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
